### PR TITLE
docs: fix CONTRIBUTING.md formatting

### PR DESCRIPTION
**Pull request by Eomm**
Fix broken links

### CODE REVIEW

**Review by davideimola — APPROVED** [review]
Ty @Eomm!

LGTM to me!

**Comment by TheJoin95** [comment]
What kind of broken link did you fix? I see now a 404. @davideimola did you check it?

**Comment by Eomm** [comment]
Before: https://github.com/Schrodinger-Hat/sh-sessions/blob/de632fce7b32329177da3810077e68f8912b2b5e/CONTRIBUTING.md

image

After:

image

I did not check if links are pointing to the wrong URL

**Comment by TheJoin95** [comment]
Yep the formatting is ok. The link was a question for @davideimola since I see this https://github.com/Schrodinger-Hat/sh-sessions/pull/23/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R158 from the changes. I was wondering if he was aware of it and if yes, why the new link is going to a 404

**Comment by davideimola** [comment]
> Yep the formatting is ok. The link was a question for @davideimola since I see this https://github.com/Schrodinger-Hat/sh-sessions/pull/23/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R158 from the changes. I was wondering if he was aware of it and if yes, why the new link is going to a 404

No I didn't check them. I think we must review all based on the content...

I'd accepted the contribution because now it works

**Pull request merged**
